wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1715308097.670353
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.5
      5: 0.13.3
      8:
      - 5
architecture:
  desc: null
  value: Unet
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
